language: go

go:
  - 1.13.x

branches: # build only on these branches
  only:
    - master

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t sillyhatxu/learning-badges .
        - docker tag sillyhatxu/learning-badges:latest sillyhatxu/learning-badges:1.0

after_success:
  - bash <(curl -s https://codecov.io/bash)